name: Build Example + Deploy to Pages, Publish Package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build_example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Pack local package
        id: pack
        run: |
          FILE=$(npm pack)
          echo "tarball=$FILE" >> "$GITHUB_OUTPUT"

      - name: Install example dependencies
        working-directory: examples
        run: npm ci

      - name: Install local package tarball into example
        working-directory: examples
        run: npm i ../${{ steps.pack.outputs.tarball }} --no-save

      - name: Build example (Vite)
        shell: bash
        working-directory: examples
        run: |
          set -euo pipefail
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          if [[ "${REPO_NAME}" == *.github.io ]]; then
            BASE="/"
          else
            BASE="/${REPO_NAME}/"
          fi
          echo "Building with base=${BASE}"
          npm run build --silent -- --base "${BASE}"

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: examples/dist

  deploy:
    needs: build_example
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



