name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (GitHub Packages)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@shashank-sharma'

      - name: Install dependencies (no scripts)
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: 'true'
        run: npm ci --ignore-scripts

      - name: Validate package can be packed (no scripts)
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: 'true'
        run: npm pack

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_IGNORE_SCRIPTS: 'true'
        run: npm publish --provenance --access public


